export enum roleType {
    CITIZEN = 'CITIZEN',
    ADMIN = 'ADMIN',
    MUNICIPALITY = 'MUNICIPALITY'
}

export enum Category {
    WATER_SUPPLY_DRINKING_WATER = 'WATER_SUPPLY_DRINKING_WATER',
    ARCHITECTURAL_BARRIERS = 'ARCHITECTURAL_BARRIERS',
    SEWER_SYSTEM = 'SEWER_SYSTEM',
    PUBLIC_LIGHTING = 'PUBLIC_LIGHTING',
    WASTE = 'WASTE',
    ROAD_SIGNS_TRAFFIC_LIGHTS = 'ROAD_SIGNS_TRAFFIC_LIGHTS',
    ROADS_URBAN_FURNISHINGS = 'ROADS_URBAN_FURNISHINGS',
    PUBLIC_GREEN_AREAS_PLAYGROUNDS = 'PUBLIC_GREEN_AREAS_PLAYGROUNDS',
    OTHER = 'OTHER'
}
